import { CreateTournament, TournamentRepository } from '@tournament/core'
import { AuthenticatedActor } from 'shared'
import { CreateTournamentInput } from '../@types'

export default class CreateTournamentController {
  constructor(private readonly tournamentRepository: TournamentRepository) {}

  // The actor (id + role) comes from the JWT; the admin role is re-checked inside
  // the use case (AdminUseCase). scheduledAt arrives as an ISO string and becomes a
  // Date. categoryIsLeaf is resolved from the category context by the backend.
  // tournamentId is pre-generated by the backend so it can create the round-0
  // matches right after this persists the aggregate.
  async execute(
    input: CreateTournamentInput,
    actor: AuthenticatedActor,
    categoryIsLeaf: boolean,
    tournamentId?: string,
  ): Promise<void> {
    const useCase = new CreateTournament(this.tournamentRepository)
    await useCase.execute(
      {
        id: tournamentId,
        title: input.title,
        categoryId: input.categoryId,
        categoryIsLeaf,
        imageUrl: input.imageUrl,
        scheduledAt: new Date(input.scheduledAt),
        rakeBasisPoints: input.rakeBasisPoints,
        size: input.size,
        participants: input.participants,
      },
      actor,
    )
  }
}
