/**
 * Domain error codes. Just stable strings — the HTTP layer (adapters/backend)
 * maps each code to a status. Keeps the domain agnostic of HTTP.
 */
export const Errors = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  REQUIRED_FIELD: 'REQUIRED_FIELD',

  // shared / money
  INVALID_AMOUNT: 'INVALID_AMOUNT',

  // auth
  INVALID_EMAIL: 'INVALID_EMAIL',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  INVALID_PASSWORD_HASH: 'INVALID_PASSWORD_HASH',
  PASSWORDS_DO_NOT_MATCH: 'PASSWORDS_DO_NOT_MATCH',
  NAME_REQUIRED: 'NAME_REQUIRED',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  PASSWORD_SAME_AS_PREVIOUS: 'PASSWORD_SAME_AS_PREVIOUS',
  INVALID_SESSION: 'INVALID_SESSION',
  NOT_ADMIN: 'NOT_ADMIN',

  // wallet
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INVALID_STAKE: 'INVALID_STAKE',
  WITHDRAWAL_TOO_LARGE: 'WITHDRAWAL_TOO_LARGE',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_SETTLED: 'PAYMENT_ALREADY_SETTLED',
  RECEIPT_REQUIRED: 'RECEIPT_REQUIRED',
  DEPOSIT_LIMIT_EXCEEDED: 'DEPOSIT_LIMIT_EXCEEDED',
  SELF_EXCLUDED: 'SELF_EXCLUDED',
  ALREADY_SELF_EXCLUDED: 'ALREADY_SELF_EXCLUDED',

  // match
  MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',
  MATCH_NOT_OPEN: 'MATCH_NOT_OPEN',
  MATCH_ALREADY_SETTLED: 'MATCH_ALREADY_SETTLED',
  NOT_A_PARTICIPANT: 'NOT_A_PARTICIPANT',
  NOT_ENOUGH_PARTICIPANTS: 'NOT_ENOUGH_PARTICIPANTS',
  INVALID_MATCH_STATUS: 'INVALID_MATCH_STATUS',
  SCHEDULED_IN_PAST: 'SCHEDULED_IN_PAST',
  DRAW_NOT_ALLOWED: 'DRAW_NOT_ALLOWED',
  INVALID_BEST_OF: 'INVALID_BEST_OF',
  INVALID_UNIT_NUMBER: 'INVALID_UNIT_NUMBER',

  // betting
  BETTING_CLOSED: 'BETTING_CLOSED',
  BET_NOT_FOUND: 'BET_NOT_FOUND',
  INVALID_COMBO_LEGS: 'INVALID_COMBO_LEGS',
  DUPLICATE_COMBO_MARKET: 'DUPLICATE_COMBO_MARKET',
  INVALID_COMBO_ODD: 'INVALID_COMBO_ODD',
  STAKE_LIMIT_EXCEEDED: 'STAKE_LIMIT_EXCEEDED',

  // category
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_NOT_LEAF: 'CATEGORY_NOT_LEAF',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',

  // participant
  PARTICIPANT_NOT_FOUND: 'PARTICIPANT_NOT_FOUND',
  PARTICIPANT_ALREADY_EXISTS: 'PARTICIPANT_ALREADY_EXISTS',
  PARTICIPANT_IN_USE: 'PARTICIPANT_IN_USE',

  // tournament
  TOURNAMENT_NOT_FOUND: 'TOURNAMENT_NOT_FOUND',
  INVALID_TOURNAMENT_SIZE: 'INVALID_TOURNAMENT_SIZE',
  NOT_ENOUGH_TOURNAMENT_PARTICIPANTS: 'NOT_ENOUGH_TOURNAMENT_PARTICIPANTS',
  DUPLICATE_PARTICIPANT_NAME: 'DUPLICATE_PARTICIPANT_NAME',
  TOURNAMENT_NOT_OPEN: 'TOURNAMENT_NOT_OPEN',
  TOURNAMENT_ALREADY_FINISHED: 'TOURNAMENT_ALREADY_FINISHED',
  BRACKET_SLOT_NOT_FOUND: 'BRACKET_SLOT_NOT_FOUND',
} as const

export type ErrorCode = (typeof Errors)[keyof typeof Errors]
