import { AdminUseCase, AuthenticatedActor, ValidationError, Errors } from 'shared'
import { Tournament } from '../model'
import { TournamentRepository } from '../providers'

interface ParticipantInput {
  displayName: string
  userId?: string | null
}

interface Input {
  // Pre-generated by the backend so it can create the round-0 matches right after
  // (kept optional: the domain generates one when absent).
  id?: string
  title: string
  categoryId: string
  // Resolved from the category context by the caller (backend) — plain data so
  // tournament does not import the category context. Must exist (checked by the
  // caller) and be a leaf (checked here).
  categoryIsLeaf: boolean
  imageUrl?: string | null
  scheduledAt: Date
  rakeBasisPoints?: number
  // How many units decide each round's confrontations, one entry per round
  // (defaults to all 1s) — see Tournament.bestOfByRound.
  bestOfByRound?: number[]
  size: number
  participants: ParticipantInput[]
}

/**
 * Admin creates a tournament. Rules (leaf category, valid size, exactly `size`
 * unique participants, start not in the past) are enforced here / in the
 * Tournament constructor, which also lays out the bracket. The round-0 matches
 * are NOT created here — that is cross-context and orchestrated by the backend
 * after this persists the aggregate. Admin-only (AdminUseCase).
 */
export default class CreateTournament extends AdminUseCase<Input, void> {
  constructor(private readonly tournamentRepository: TournamentRepository) {
    super()
  }

  protected async executeAsAdmin(input: Input, actor: AuthenticatedActor): Promise<void> {
    if (!input.categoryIsLeaf) {
      ValidationError.throwError(Errors.CATEGORY_NOT_LEAF, input.categoryId)
    }

    const tournament = new Tournament({
      id: input.id,
      creatorId: actor.id,
      title: input.title,
      categoryId: input.categoryId,
      imageUrl: input.imageUrl,
      scheduledAt: input.scheduledAt,
      rakeBasisPoints: input.rakeBasisPoints,
      bestOfByRound: input.bestOfByRound,
      size: input.size,
      participants: input.participants,
    })

    await this.tournamentRepository.create(tournament)
  }
}
